# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 2.0.0-appveyor-testing-{build}


cache:
  # Cache downloaded pip packages.
  - "C:\\Users\\appveyor\\AppData\\Local\\pip"


#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Windows Server 2012

environment:
  matrix:
    - PYTHON: "c:\\python27"
      WHL_ARCH: 32

    - PYTHON: "c:\\python27-x64"
      WHL_ARCH: _amd64

  global:
    MCEDIT_BUILD_VERSION: $(APPVEYOR_REPO_TAG_NAME)


# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - pip install https://github.com/mcedit/mcedit2-deps/raw/master/wheels/PySide-1.2.2-cp27-none-win%WHL_ARCH%.whl
  - pip install -r requirements.txt
  - pip install git+http://github.com/pyinstaller/pyinstaller@5f91905

build_script:
  - pyinstaller mcedit2.spec

artifacts:
  - path: dist/mcedit2-*.exe

deploy:
  description: 'MCEdit 2 beta release $(APPVEYOR_REPO_TAG_NAME)'
  provider: GitHub
  auth_token: "$(GITHUB_AUTH_TOKEN)"
  artifact: /dist\/mcedit2-.*\.exe/
  draft: false
  prerelease: true
  force_update: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only